module.exports = {
  products: [
    {
      _id: '1',
      name: 'Yasuke the Black Samurai Barbell End Cap',
      category: 'Stainless Steel endCaps',
      image: '/images/product-1.png',
      price: 20,
      brand: 'Emblems',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Bull Strength Barbell End Cap',
      category: 'Stainless Steel endCaps',
      image: '/images/product-2.png',
      price: 20,
      brand: 'barbellEndCaps',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Reaper Barbell End Caps ',
      category: 'Stainless Steel endCaps',
      image: '/images/product-3.png',
      price: 16,
      brand: 'Caps',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Goat Barbell End Caps',
      category: 'Aluminum endCaps',
      image: '/images/product-4.png',
      price: 12,
      brand: 'Custom EndCaps',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'The Lion Spirit End Cap',
      category: 'Aluminum endCaps',
      image: '/images/product-5.png',
      price: 15,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Warrior Ape End Caps',
      category: 'Aluminum endCaps',
      image: '/images/product-6.png',
      price: 15,
      brand: 'War Caps',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};